name: Nightly Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1

      - name: Run zig fmt check
        run: zig fmt --check .

      - name: Run debug build
        run: zig build build-wasm
