name: Nightly Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Run zig fmt check
        run: zig fmt --check .

      - name: Build zero-init, zero-convert, and demo_application (debug build)
        run: zig build

      - name: Setup demo_application web application
        run: zig build build-wasm

      - name: Host demo_application web application
        run: |
          zig build run-wasm &
          sleep 15
          curl http://127.0.0.1:8000/demo_application.htm --output test1 \
          && curl http://127.0.0.1:8000/zero-graphics.js --output test2 \
          && curl http://127.0.0.1:8000/demo_application.wasm --output test3
